spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-location: "file:///C://practice/documents//msconfigs//config"
        git:
          uri: "https://github.com/Sofimedina/ms-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "3442H445FKK9HB3KKK9L45A13"

server:
  port: 8071
